default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  username: jeko
  password: 123456
  pool: 5

development:
  <<: *default
  database: testpuzzle_development

production:
  <<: *default
  database: testpuzzle_production
